# Generated by Django 5.2.8 on 2025-11-12 02:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='null', max_length=255, verbose_name='image'),
        ),
    ]
